services:
  server:
    image: server-app:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      # - SPRING_REDIS_PASSWORD=yourpassword #
      - SPRING_REDIS_SSL_ENABLED=false
    depends_on:
      - redis
    networks:
      - codecafe_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "--spider",
          "http://localhost:8080/actuator/health",
          "||",
          "exit",
          "0",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: "http://localhost:8081"
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - codecafe_network
    environment:
      - VITE_BACKEND_URL=http://localhost:8081
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "--spider",
          "http://localhost:80",
          "||",
          "exit",
          "0",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - codecafe_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping", "||", "exit", "0"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  codecafe_network:
    driver: bridge

volumes:
  redis-data:
